apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grpc-notifications
  name: grpc-notifications
spec:
  ports:
    - name: "50054"
      port: 50054
      protocol: TCP
      targetPort: 50054
  selector:
    app: grpc-notifications
  type: ClusterIP
status:
  loadBalancer: {}
