version: "3"

services:
  users-ms:
    build: ./ms-users
    ports:
      - "8089:8089"
    volumes:
      - ./ms-users/src:/usr/src/app/src
    command: go run main.go
    networks:
      - nest-grpc-network

  zonas-ms:
    build: ./ms-zonas
    ports:
      - "50052:50052"
    volumes:
      - ./ms-zonas/src:/usr/src/app/src
    command: npm run start:dev
    networks:
      - nest-grpc-network

  reservas-ms:
    build: ./ms-reservas
    ports:
      - "50051:50051"
    volumes:
      - ./ms-reservas/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - ZONES_GRPC_SERVER_URL=zonas-ms:50052
      - NOTIFICATIONS_GRPC_SERVER_URL=notifications-ms:50054
      - GRPC_SERVER_URL=users-ms:8089
    networks:
      - nest-grpc-network

  notification-ms:
    build: ./ms-notifications
    ports:
      - "50054:50054"
    volumes:
      - ./ms-notifications/src:/usr/src/app/src
    command: npm run start:dev
    networks:
      - nest-grpc-network

  client-gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - GRPC_SERVER_URL=users-ms:8089
      - ZONES_GRPC_SERVER_URL=zonas-ms:50052
      - BOOKINGS_GRPC_SERVER_URL=reservas-ms:50051
      - PORT=4000
    depends_on:
      - users-ms
      - zonas-ms
      - reservas-ms
    networks:
      - nest-grpc-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: npm run dev
    environment:
      - GATEWAY_GRPC_SERVER_URL=client-gateway:4000
    depends_on:
      - client-gateway
    networks:
      - nest-grpc-network

networks:
  nest-grpc-network:
    driver: bridge
