version: "3"

services:
  users-ms:
    build: ./ms-users
    ports:
      - "8089:8089"
    volumes:
      - ./ms-users/src:/usr/src/app/src
    command: go run main.go
    networks:
      - nest-grpc-network

  client-gateway:
    build: ./gateway
    ports:
      - 4000:4000
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - GRPC_SERVER_URL=users-ms:8089
      - PORT=4000
    depends_on:
      - users-ms
    networks:
      - nest-grpc-network

networks:
  nest-grpc-network:
    driver: bridge
