apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grpc-gateway
  name: grpc-gateway
spec:
  ports:
    - name: "4000"
      port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: grpc-gateway
  type: NodePort
status:
  loadBalancer: {}
