apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grpc-users
  name: grpc-users
spec:
  ports:
    - name: "8089"
      port: 8089
      protocol: TCP
      targetPort: 8089
  selector:
    app: grpc-users
  type: ClusterIP
status:
  loadBalancer: {}
