apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grpc-reservas
  name: grpc-reservas
spec:
  ports:
    - name: "50051"
      port: 50051
      protocol: TCP
      targetPort: 50051
  selector:
    app: grpc-reservas
  type: ClusterIP
status:
  loadBalancer: {}
